### ISSUE TITLE
Purpose of connections lookup object in chatClient.js

### ISSUE THREAD

**Issue by gptucci** [conficient/BlazorChatSample#25]
Hi
You demo is awesome: really tnx.
Just a stupid question: what is the purpose of connections lookup object in chatClient.js ?
We can have only 1 connection in this sample.
Why not use a simple object ?
Tnx

**Comment by conficient** [comment]
In the example I have only one chat window, true - but there are lots of cases where you can have multiple clients talking to SignalR and then you'd need to differentiate between them. 

For example I have a log monitoring page on an app that displays Serilog messages from several subsystems via SignalR - they would need to be able to work on the same page using the same JS code.
