### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by Ricardoaraujo00** [conficient/BlazorChatSample#28]
The project cannot be opened in visual studio and when i try to run with dotnet run i get this error that only happens with this application:
Found .NET Core SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\3.1.100\dotnet.dll]

**Comment by conficient** [comment]
This uses the latest version of the .NET Core SDK preview version and Visual Studio 2019 preview.

Follow the instructions at [Blazor Getting Started](
https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
