### ISSUE TITLE
private chat

### ISSUE THREAD

**Issue by drma-tech** [conficient/BlazorChatSample#37]
as I understand it this is a public chat, where anyone who enters talks with everyone. don't have a way to make a hub between two people only?

**Comment by drma-tech** [comment]
I was researching here and I saw that you have a group concept. would it be ideal to create a group between two people or would there be a better way to resolve?

**Comment by conficient** [comment]
In the example I created it's a group chat, but SignalR does support doing one-to-one or subgroups - I have not created that in the example as it would dilute the example. I suggest you research one-to-one chat using SignalR generally, and that would explain how to do it.
