### ISSUE TITLE
Update to new Blazor JsInterop

### ISSUE THREAD

**Issue by DNF-SaS** [conficient/BlazorChatSample#4]

**Comment by conficient** [comment]
What new interop is this? I used the 0.4.0 version

**Comment by DNF-SaS** [comment]
In the 0.5-preview builds, the whole JsInterop changed - e.g. Blazor.registerFunction() does not exist any more.

**Comment by conficient** [comment]
OK thanks for the heads-up - I will update to 0.5.0 when it's released

**Comment by conficient** [comment]
Upgraded
